export const LISTAR_TAREFAS    = 'LISTAR_TAREFAS'
export const CRIAR_TAEFA       = 'CRIAR_TAEFA'
export const EDITAR_TAREFA     = 'EDITAR_TAREFA'
export const DELETAR_TAREFA    = 'DELETAR_TAREFA'
export const SELECIONAR_TAREFA = 'SELECIONAR_TAREFA'
export const SETAR_ERRO        = 'SETAR_ERRO'
